# Generated by Django 5.0.6 on 2024-05-24 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('street', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=6)),
                ('subjects', models.TextField()),
                ('previous_school', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studmanage.city')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studmanage.state')),
            ],
        ),
    ]
