# Generated by Django 5.0.6 on 2024-05-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studmanage', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='previous_school',
            field=models.JSONField(),
        ),
    ]
