# Generated by Django 5.0.6 on 2024-05-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studmanage', '0003_alter_student_previous_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.JSONField(),
        ),
    ]
