# Generated by Django 5.0.6 on 2024-05-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studmanage', '0010_alter_student_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
