# Generated by Django 5.0.6 on 2024-05-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studmanage', '0012_student_previous_schooling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='previous_schooling',
        ),
    ]
