# Generated by Django 5.0.6 on 2024-05-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studmanage', '0013_remove_student_previous_schooling'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='previous_schooling',
            field=models.JSONField(default=list),
        ),
    ]
