# Generated by Django 5.0.6 on 2024-05-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studmanage', '0014_student_previous_schooling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='previous_schooling',
            field=models.JSONField(default=list, null=True),
        ),
    ]
